services:

  traefik:
    image: traefik:v3.5
    container_name: traefik

    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=ab2737@njit.edu"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

    restart: unless-stopped

  production:
    image: ghcr.io/ab2737/angelo-selfhost-cicd:prod
    container_name: production-site

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.production.rule=Host(`angelobustamanteselfhost.com`)"
      - "traefik.http.routers.production.entrypoints=websecure"
      - "traefik.http.routers.production.tls=true"
      - "traefik.http.routers.production.tls.certresolver=letsencrypt"
      - "traefik.http.services.production.loadbalancer.server.port=80"

    restart: unless-stopped

  qa:
    image: ghcr.io/ab2737/angelo-selfhost-cicd:qa
    container_name: qa-site

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qa.rule=Host(`qa.angelobustamanteselfhost.com`)"
      - "traefik.http.routers.qa.entrypoints=websecure"
      - "traefik.http.routers.qa.tls=true"
      - "traefik.http.routers.qa.tls.certresolver=letsencrypt"
      - "traefik.http.services.qa.loadbalancer.server.port=80"

    restart: unless-stopped
